blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/hassaku63/find-serverless-stacks/security/advisories
    about: Please report security vulnerabilities through GitHub Security Advisories